version: '3'
services:
  email_backend:
    build: 
      context: .
      dockerfile: prod.dockerfile
    image: phk13/email:0.0.1
    environment:
      BOOTSTRAP_SERVERS: pkc-ewzgj.europe-west4.gcp.confluent.cloud:9092
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:     -
      SASL_PASSWORD:     -
      SASL_MECHANISM:    PLAIN
      KAFKA_TOPIC:       email_topic
      EMAIL_HOST:        smtp.mailtrap.io
      EMAIL_PORT:        2525
      EMAIL_USERNAME:    -
      EMAIL_PASSWORD:    -

        
