version: '3.9'
services:
  checkout_backend:
    build: .
    command: "go run main.go"
    ports:
      - 8004:8000
    volumes:
      - .:/app
    depends_on:
      - checkout_db
    networks:
      - checkout
      - users

  checkout_queue:
    build: .
    command: "go run src/commands/consumer.go"
    depends_on:
      - checkout_db
      - checkout_backend
    networks:
      - checkout


  checkout_db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 37066:3306
    networks:
      - checkout

networks:
  users:
    external:
      name: users
  checkout:
