version: '3.9'
services:
  admin_backend:
    build: .
    command: "go run main.go"
    ports:
      - 8002:8000
    volumes:
      - .:/app
    depends_on:
      - admin_db
    networks:
      - admin
      - users

  admin_queue:
    build: .
    command: "go run src/commands/consumer.go"
    depends_on:
      - admin_db
      - admin_backend
    networks:
      - admin


  admin_db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 35066:3306
    networks:
      - admin

networks:
  users:
    external:
      name: users
  admin:
