version: '3.9'
services:
  users_backend:
    build: .
    container_name: users-ms
    volumes:
      - .:/app
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 34066:3306
    networks:
      - users
  
networks:
  users:
    name: users
