version: '3'
services:
  users-backend:
    build:
      context: .
      dockerfile: prod.dockerfile
    image: phk13/users:0.0.2
    ports:
      - 8001:8000
    environment:
      DB_HOST: -
      DB_PORT: 3306
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: root